kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
spec:
  storageClassName: nfs-client #--- Need to be linked to the one created above storageclass The names are the same 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi